### ISSUE TITLE
Fritzbox 5490 FTTH

### ISSUE THREAD

**Issue by dschaefer79** [olistudent/FBEditor#21]
Hi,

I have edited the configuration of the Fritzbox 5490 FTTH with FBedit but when I save it to the fritzbox the changes don't stay in the config.

My firmware is 151.06.51.

Does fbeditor work with Fritzbox 5490 ?

Thanks,

Dominique

**Comment by dschaefer79** [comment]
It's working with your last version, I wasn't using the last version

**Comment by olistudent** [comment]
Okay, which version did work for you? I don't have a box with actual firmware. But I doubt that the last version is from me!? :-)

**Comment by dschaefer79** [comment]
I have used the 0.7.2.1 version 

Thanks
