### ISSUE TITLE
SID is not calculated right

### ISSUE THREAD

**Issue by lemrm** [olistudent/FBEditor#22]
`(08.03.18 20:45:47): DEBUG: Challenge: 4da9a4fd Response: 4da9a4fd-56edd1747247a
d8c76ccad1220d587b
(08.03.18 20:45:47): DEBUG: login_lua Response: <?xml version="1.0" encoding="ut
f-8"?><SessionInfo><SID>0000000000000000</SID><Challenge>0a16a876</Challenge><Bl
ockTime>128</BlockTime><Rights></Rights></SessionInfo>`

could you guide me in witch class your'e doing the md5 hash of %CHALLANGE%-%SECRET%

for me this is working

```
if NOT %SID% NEQ 0000000000000000 ( set "CPSTR=%CHALLANGE%-%SECRET%" ) 
                
                echo|set /p="%CPSTR%">var.txt<nul
                          
                          iconv -f iso-8859-1 -t utf-16le var.txt>var-utf16.txt
			 
                          fciv.exe -md5 var-utf16.txt>var-hash-fciv.txt
```

**Comment by olistudent** [comment]
Hi. 

If you have not already found yourself. The SID is calculated in SIDLogin.java. Did AVM change the calculation in one of the last firmware versions?

Regards,
Oliver

**Comment by olistudent** [comment]
Closed. No reaction.
