### ISSUE TITLE
Exception in thread "AWT-EventQueue-0"

### ISSUE THREAD

**Issue by rubenkr** [olistudent/FBEditor#24]
In the latest FBEditor-0.7.2.1.jar 

I get the following error with my FB 6360 OS 06.51:

(01.05.18 14:56:54): OS Language: de
(01.05.18 14:56:54): OS Country: DE
(01.05.18 14:56:54): Selected language: de_DE
(01.05.18 14:56:54): INFO: Loading locale: de_DE
(01.05.18 14:56:54): Java version: 9.0.4
Font: : Consolas
Debug boxtype: 85
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.desktop/javax.swing.text.AbstractDocument$DefaultDocumentEventUndoableWrapper cannot be cast to java.desktop/javax.swing.text.AbstractDocument$DefaultDocumentEvent

How can I fix this? Thanks and KR

**Comment by olistudent** [comment]
Sounds like a problem with the Java version!? Or does it really depend on the bxo type and version?

I don't have a Fritzbox close to me neither Java 9.0.4...

**Comment by mypikachu** [comment]
Ist ein Bug in Java 9 und 10, wird gefixt in den nächsten Tagen mit einem kleinen zwischenupdate ohne Versionsänderung, Sorry.

**Comment by mypikachu** [comment]
Hier mal ein kleines Update zum Bug in Java 9 und 10 ab Heute 08.05.2018,

Teste bitte mal diese FBEditor Version 0.6.9.7c: https://github.com/mypikachu/FBEditor/releases/tag/v0.6.9.7

und sage ob es jetzt geht, ein Update zur Version 0.7.2.1 wird noch folgen.

**Comment by olistudent** [comment]
Closed. New versions should work with Java 9 and 10.
