### ISSUE TITLE
How to start in English

### ISSUE THREAD

**Issue by bovirus** [olistudent/FBEditor#29]
The program start in German language.

Is there a way via command line to start it in English?

**Comment by mypikachu** [comment]
Das sollte jetzt ab dieser Testversion FBEditor Version 0.6.9.7g(0.6.9.13/0.6.9.7=a) gehen, zwar nicht per Command line,
aber durch die Anpassung des Files: FBEditor.properties.xml
Info hier: https://www.ip-phone-forum.de/threads/fbeditor.79513/page-83#post-2283000

**Comment by bovirus** [comment]
@olistudent 

OK. Thanks.
Please close the ticket.

**Comment by mypikachu** [comment]
T'ja hatte mir in den letzten Tagen schon mal überlegt ob ich die manuelle Language Einstellung, 
vorrübergehend mal über ein Menü Eintrag löse, bis der von mir schon lange geplante Dialog 
für die nötigsten Grundeinstellungen erstellt ist, es fehlt mir aber immer die Zeit dazu Sorry.

**Comment by olistudent** [comment]
Close ticket as requested.
