### ISSUE TITLE
Added Italian language

### ISSUE THREAD

**Issue by bovirus** [olistudent/FBEditor#30]
Hi.

Added Italian language.

https://github.com/olistudent/FBEditor/pull/28

Please rebuild it to include it.

**Comment by bovirus** [comment]
Or if you modify teh code to check OS language.
If it's available the language that match OS langauge use it (es OS langaueg =it - FbEditor language = it).
Otherwise use by default English.

Or if it's too complex to enable it in the code use different **_FB-Editor-x.xxx-zz.jar_** where **_zzz_** = **_language (de/it/en/es)_**

Thanks.

**Comment by mypikachu** [comment]
Die Funktion ist schon vorhanden, hat nur einen Fehler hier:

`		if (language == null || language.equals(false)) {
			Debug.info("No language set yet ... Setting language to OS language");
			// Check if language is supported. If not switch to English
			if (supported_languages.contains(new Locale(System
					.getProperty("user.language"), System
					.getProperty("user.country")))) {
				language = System.getProperty("user.language") + "_"
						+ System.getProperty("user.country");
			} else {
				Debug.warning("Your language ist not yet supported.");
				language = "en_US";
}`

habe es jetzt mal geändert und hoffe dass jetzt die Language richtig erkannt wird hier: 

`		if (language == null || !language.equals(System.getProperty("user.language") + "_" + System.getProperty("user.country"))) { // 22.06.2018
			Debug.info("No language set yet ... Setting language to OS language");
			// Check if language is supported. If not switch to English
			if (supported_languages.contains(new Locale(System
					.getProperty("user.language"), System
					.getProperty("user.country")))) {
				language = System.getProperty("user.language") + "_"
						+ System.getProperty("user.country");
			} else {
				Debug.warning("Your language ist not yet supported.");
				language = "en_US";
			}
		}`

Muss erst noch einen anderen Fehler beheben, dann werde ich eine neue Testversion zum Download reinstellen.

**Comment by bovirus** [comment]
OK thanks.
I will wait the new java version to test.

**Comment by mypikachu** [comment]
Aktuelle Testversion hier: FBEditor Version 0.6.9.7d

https://github.com/mypikachu/FBEditor/releases/tag/v0.6.9.7d

Ich hoffe damit klappt die Language Erkennung für de_DE / en_US / es_ES / it_IT jetzt ?!

**Comment by bovirus** [comment]
Thanks.

The problem is that if you try to edit the languaege directly on Github, Github works only with UTF-8 then the accented letters can be converted.

Thanks again.

**Comment by mypikachu** [comment]
Nur zur Info hier: https://github.com/olistudent/FBEditor/issues/26#issuecomment-391714658
FBEditor 0.6.9.7c/0.6.9.7e(0.6.9.11) und FBEditor 0.7.2.1c/0.7.2.1e(0.7.2.5) sind von der Entwicklung gleich, bis auf eines im FBEditor 0.7.2.1c/0.7.2.1e(0.7.2.5)
fehlt zur Zeit noch die Funktion für das Kennwort der Sicherungsdatei.

Es war von mir eigentlich keine neue Version 0.7.2.1 mehr geplant da es sich hier noch
um den Alten FBEditor handelt bei dem man noch kein Kennwort für die Sicherungsdatei eigeben kann,
aber wegen dem Java 9 Fehler hier: https://github.com/olistudent/FBEditor/issues/24
08.05.2018 Bug Fix zu Java 9 und 10 -> FBEditor Version 0.7.2.1c
habe ich es jetzt Aktuallisiert.

Die FBEditor Version 0.6.9.7 wird die FBEditor Version 0.7.2.1 in zukunft mit einer neuen Versionsnummer ablösen,
dann wird es auch nur noch eine Aktuelle Version geben, und nicht mehr zwei wie es jetzt noch der Fall ist Sorry.

**Comment by bovirus** [comment]
@mypikachu

Thanks for the feedback about the typo error on entry key on HWU forum. Fixed.

Thanks for the unique version number.
I believe that different version 0.6.x.x and 0.7.x.x can create misunderstanding about latest one.

**Comment by mypikachu** [comment]
Sorry, hast es wohl Überlesen,
das hier: 
`<entry key="language">en_EN</entry>`
sollt eigentlich so sein:
`<entry key="language">en_US</entry>`

Sorry, ich hatte die Versionsnummer bei nem Bugfix oder einer kleinen Änderung 
jetzt per Buchstaben hochgezählt weil die Download Links sehr verbreitet sind und man schneller die Aktuelle Versionsänderung Findet, 
sonst würde man sich nen Wolf Suchen, wenn ich wieder was Lösche und der Link nicht mehr geht,
aber bei der nächsten grossen Änderung im FBEditor wird es eine neue Version mit einem neuen Link geben.

Sorry, mir Fehlt leider etwas die Zeit für die Anpassung zum Dialog mit der IP/Password/Benutzer und Kennwort eingabe,
wollte es schon lange zusammen legen, aber wenn der Temöräre Fehler Fritzbox nicht gefunden auftritt, mal im Menü auf Neuverbinden gehen oder im Menü mal die IP Eingabe öffnen und mit OK Beenden dann sollte sich der FBEditor wieder mit der FritzBox verbinden,
vorrausgesetzt IP/Password und Benutzer sind Korrekt eingetragen.

**Comment by bovirus** [comment]
@mypikachu

Thanks for the explanation.
I made two pullup requests for master & 0.6.9.7e version about Italian language.
If you can please merge it.

**Comment by mypikachu** [comment]
@olistudent

Could be possible to post in home page of github repository the link of Italian forum like

DE -http://www.ip-phone-forum.de/showthread.php?t=79513
IT - https://www.hwupgrade.it/forum/showthread.php?p=45620145

Thanks.

https://github.com/mypikachu/FBEditor/pull/5#issuecomment-399921821

Sorry bovirus, das kann nur Oliver entscheiden der das Programm mal Entwickelt hat, 
und zur Zeit wohl keine FritzBox hat und auch keine Zeit um es weiter zu Pflegen.

Gruß Erwin

**Comment by mypikachu** [comment]
Überprüfe Bitte mal das Neu erstellte Language File für Italien, auf korrekte schreibweise und übersetzung, 
wenn darin noch ein Fehler enthalten ist dann teile mir das Bitte mit.

Language Änderungen in Eclipse 4 Bitte in zukunft mit dem passenden Plugin: ResourceBundle Editor (http://essiembre.github.io/eclipse-rbe/)
um zukünftige Fehler zu vermeiden Danke.

**Comment by bovirus** [comment]
@mypikachu 

Thanks.
The language file now is ok.
Accented letters are ok.
Its enough to use a language file coded as ANSI or UTF-8 (not UCS-2 LE as was in the past)

I will use Resource Bundle Editor in the future. Thanks.

**Comment by olistudent** [comment]
Closed. Merged pull request.
