### ISSUE TITLE
Fist program start ask ip/password - On next start didn't ask them

### ISSUE THREAD

**Issue by bovirus** [olistudent/FBEditor#31]
@mypikachu 

Is it normal that at first start (with xml configuration file empty) the java application ask for modem IP & password , and on the next start (after creation of xml configuration file) didn't ask anymore and start directly with message "FRITZ!box not found"?

Could be possible to modify the java app to ask every time modem IP & password?

Thanks.

**Comment by bovirus** [comment]
@olistudent 

Could be possible to implement the function required?
Thanks.

**Comment by mypikachu** [comment]
> Could be possible to modify the java app to ask every time modem IP & password?

Sorry, ich halte das im Moment gerade nicht für Sinnvoll, wenn man nur einen Dialog hätte,
für die Eingabe dass wäre ja noch OK, wenn aber hintereinander vier Dialoge aufpoppen
bei jeden Neustart das nervt schon ganz schön, Sorry.

Über einen Eintrag im Menü könnte man es ein oder aus schalten für jeden neustart,
und dazu müsste auch noch das File: FBEditor.properties.xml angepasst werden, 
damit die Einstellung nicht verloren geht.

**Comment by bovirus** [comment]
@mypikachu 

OK. Thanks.

**Comment by mypikachu** [comment]
Mit der Testversion 0.6.9.7h sollte jetzt gehen.

**Comment by olistudent** [comment]
Solved by mypikachu. Thank you.
