### ISSUE TITLE
version 0.6.9.7g - separate tag and exe version

### ISSUE THREAD

**Issue by bovirus** [olistudent/FBEditor#33]
@mypikachu 

Could you please make a separate tag for version 0.6.9.7g here (moving 0.6.9.7g.raj from tag 0.,6.9.7e) here

https://github.com/mypikachu/FBEditor/tags

and put in tag 0.6.9.7g both version jar and exe as you did for 0.6.9.7e?

What program are you using to convert jar in exe?

Thanks.

**Comment by mypikachu** [comment]
> separate tag

Wird es erst bei der nächsten Testversion geben wo hoffentlich die kleinen Anzeige Fehlerchen zum 
anpassen für IT Language behoben sind.

Da es sich bei den Versionen hier: 0.6.9.7d-g bis jetzt nur um vorab Testversionen handelt, 
wird der Alte Tag 0.6.9.7e bei einer der nächsten Testversion mit neuem Tag wieder gelöscht, 
(damit man sich die alten Fehler im Quellcode der Source code (zip) nicht wieder einfängt) Sorry.

Exe zur 0.6.9.7g wird noch folgen aber erst in der nächsten Testversion 0.6.9.7 Sorry.

**Comment by bovirus** [comment]
@mypikachu 

The program name in the title is **_Fritz!Boz Export Editor_**. **_FBEditor_** is just an acronym. 
I believe that the program name in github title and in file name should be 
**_FRITZ!Box Export Editor_** because **_FRITZ!Box_** is an copyright name.
