### ISSUE TITLE
Wiki zum FBEditor

### ISSUE THREAD

**Issue by mypikachu** [olistudent/FBEditor#34]
@olistudent 

Ich habe es hier: https://github.com/mypikachu/FBEditor/wiki
mal versucht eine kleine Info zu erstellen, wenn du es mal Anschauen könntest,
ob es einigermassen Ok ist, und mir Sagen könntest was man noch Ändern könnte Danke.

Bei den zusätzlichen Infos in der History zu den von mir hinzugekommenen Versionsnummern 
habe ich nur die wichtigsten Änderungen dazugenommen hoffe ich da ich mir auch 
nicht alles merken kann was ich noch in den letzten Jahren geändert hatte.

**Comment by olistudent** [comment]
Sieht gut aus. Soll ich das so übernehmen oder warum fragst du mich? :-)

Gruß,
Oliver

**Comment by bovirus** [comment]
@mypikatchu
@olistudent

Could you please open a wiki page in English?

Could you please open a wiki page in Italian (I can pass you the translation and you can add the reference to Italian thread about FBEditor).

Could you please describe how to compile myself the source code to get new jar version basing on latest version of source code?

Thanks.

**Comment by olistudent** [comment]
Opened a wiki page and copied the text from mypikachu's. Thank you.

**Comment by olistudent** [comment]
Close issue.
