### ISSUE TITLE
FBEditor 0.7.2.3

### ISSUE THREAD

**Issue by bovirus** [olistudent/FBEditor#35]
@olistudent 

Where can I downlaod FBEditor 0.7.2.3 jar file?

@mypikachu 

In your repository are not included latest commits of FBEditor 0.7.2.3.
In your site is not available "Issue" tab. Please add it.

**Comment by MikeZuluUSA** [comment]
same over here; could use the *.jar-File or a short FAQ how to build a JAR-File on my own, based on the source.zip

**Comment by olistudent** [comment]
Sorry. I don't have released version 0.7.2.3. I have only merged mypikachu's commits into the repo.

**Comment by mypikachu** [comment]
https://github.com/mypikachu/FBEditor/wiki/History

0.7.2.3 (10.05.2018)

    Inoffizielles Release 0.7.2.1c
    Inoffizielles Release von pikachu

Letztes Aktuelles Release

0.7.2.8 (29.06.2018)

    Inoffizielles Release 0.7.2.1h
    Inoffizielles Release von pikachu

Download Hier: https://github.com/mypikachu/FBEditor/releases/tag/v0.7.2.1
oder https://github.com/mypikachu/FBEditor/releases

**Comment by MikeZuluUSA** [comment]
Thx for replying. So which is the newest and most recommend version.
I am currently using FBEditor-0.6.9.7h. This version works good with 7490 - 07.08-65776 BETA and even with the 1750E - 07.08-65779 BETA.
