### ISSUE TITLE
Use FBEditor-like API to dynamically block IPs

### ISSUE THREAD

**Issue by Bluscream** [olistudent/FBEditor#36]
I have a FB7490 and i would like to use something like FBE to block IP's from reaching even the FB when they match certain fail2ban rules. Is that something that can be done with python or a internal webserver?

**Comment by olistudent** [comment]
I don't know if this is possible. FBEditor is only a graphical interface to edit some knobs of the FritzBox configuration. So pleas ask this question in the IP-Phone-Forum section or at some other place. This here is an issue tracker.

Regards,
Oliver

**Comment by Bluscream** [comment]
Issues are often used for questions aswell, hence every repo has a "question" label by default. You made the application so you should be able to give on information to wether its viable or not

Grüße, Bluscream
